# Generated by Django 4.2.2 on 2023-07-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=256)),
                ('practitioner_name', models.CharField(max_length=256)),
                ('practitioner_profession', models.CharField(max_length=256)),
                ('practitioner_sex', models.CharField(max_length=256)),
                ('practitioner_lang', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
                'unique_together': {('name', 'practitioner_name')},
            },
        ),
    ]
