# Generated by Django 4.2.2 on 2023-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_info_address_alter_info_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
